# Website settings
url: "https://xxuxian.github.io/"
# icon: "/assets/img/icons/xx.jpg"

# Internal nav
nav:
  main:
    # home: "/"
    Publication: "/research"
    Creations: "/creations"
    Talks and Outreach: '/talks'
    Awards: '/awards'
    Life: "/photos"
    CV: "/CV"
    
    

  # blogs:
  #   all: "/writing"
  #   popular: "/writing/popular"
  #   tags: "/writing/tags"
  #   rss: "/feed.xml"

# Bio settings
name: "Xian Xu"
description: "The home page of Xian Xu"
thumbnail_path: "xian.jpg"


# URLs
contact_urls:
  # twitter:
  #   url: "https://twitter.com/brikis98"
  #   label: "Twitter"
  #   icon: "twitter-square"
  #   username: "@brikis98"
  # linkedin:
  #   url: "https://www.linkedin.com/in/jbrikman"
  #   label: "LinkedIn"
  #   icon: "linkedin-square"
  # facebook:
  #   url: "https://www.facebook.com/brikis98"
  #   label: "Facebook"
  #   icon: "facebook-square"
  # slideshare:
  #   url: "https://www.slideshare.net/brikis98"
  #   label: "SlideShare"
  #   icon: "slideshare"
  github:
    url: "https://github.com/xxuxian"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "xian.xu@connect.ust.hk"
    label: "Email"
    value: "xian.xu@connect.ust.hk"
    icon: "envelope-square"
  

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
